version: "3.9"
services:
  media-monks-challenge:
    build: 
      context: ./..
      dockerfile: ./.docker/dockerfile
    volumes:
       - sqllitedata:/usr/src/app/data
    ports:
      - "8999:8999"
      - "8000:8000"
volumes:
  sqllitedata: